name: Bug Report
description: Create a bug report to help us keep track of all bugs that have to be fixed
title: "[BUG] <title>"
labels: [bug]

body:
  - type: "checkboxes"
    id: "i-have-checked"
    attributes:
      label: "I have checked that..."
      options:
        - label: "...I am using the latest version of HMCWraps"
          required: true
        - label: "...I have checked if any similar bug reports exist"
          required: true
        - label: "...I have checked if I am using a supported Minecraft version"
          required: true
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
      description: "A full description of the bug"
    validations:
      required: true
  - type: "textarea"
    id: "reproduce"
    attributes:
      label: "Steps to reproduce"
      description: "Explain how to reproduce this issue step-by-step, in as much detail as possible."
    validations:
      required: true
  - type: "textarea"
    id: "hmcw-version"
    attributes:
      label: "Plugin Version"
      description: "Run `version HMCWraps` in your console and paste the output"
    validations:
      required: true
  - type: "textarea"
    id: "server-version"
    attributes:
      label: "Server Version"
      description: "Run `version` in your console and paste the output."
    validations:
      required: true
- type: "dropdown"
  id: "type"
  attributes:
    label: "How breaking is the bug?"
    options:
      - "**Breaking Bug** - Plugin unusable"
      - "**Non-breaking Bug** - Plugin still usable, but certain features unavailable"
      - "**Minor Bug** - Plugin completely functional, but features have non-working aspects"
  validations:
    required: true
